src/main/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('pages.urls')),
]

src/pages/urls.py
from django.urls import path

from .views import (
    HomePageView,
)

app_name = 'pages'

urlpatterns = [
    path('', HomePageView, name='home'),
]

src/pages/models.py
from django.db import models

# Create your models here.

src/pages/views.py
from django.shortcuts import render

def HomePageView(request):
    context = {}
    context['msg'] = 'The View is Functioning'
    return render(request, 'pages/home-page.html', context)

src/pages/templates/pages/base.html
<!DOCTYPE html>
<html lang="en">

<head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">

    <title>BoilerPlate.21131 - {% block page_title_tag %} Pages {% endblock %}</title>
    <meta content="{% block page_meta_description %} description {% endblock %}" name="description">
    <meta content="{% block page_meta_keywords %} keywords {% endblock %}" name="keywords">

    <!-- Favicons -->
    <!--<link href="assets/img/favicon.png" rel="icon">
    <link href="assets/img/apple-touch-icon.png" rel="apple-touch-icon">-->

    <!-- Google Fonts -->
    <link href="https://fonts.googleapis.com/css?family=Open+Sans:300,300i,400,400i,600,600i,700,700i|Nunito:300,300i,400,400i,600,600i,700,700i|Poppins:300,300i,400,400i,500,500i,600,600i,700,700i" rel="stylesheet">

    <!-- Bootstrap CSS -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0/dist/css/bootstrap.min.css" rel="stylesheet"
          integrity="sha384-wEmeIV1mKuiNpC+IOBjI7aAzPcEZeedi5yW5f2yOq55WWLwNGmvvx4Um1vskeMj0" crossorigin="anonymous">

    <!-- Custom Styles for this Template -->
    <link href="static/css/base.css" rel="stylesheet">

</head>

<body>
    <!-- ======= Header/Navigation ======= -->
    <div class="container-fluid">
        {% include 'pages/partials/header.html' %}
    </div>


    <div class="container">
        {% block content %}
            BODY
        {% endblock %}
    </div>

    <!-- ======= Footer ======= -->
    <div class="container-fluid">
        {% include 'pages/partials/footer.html' %}
    </div>


    <!-- Custom JavaScript for this Template -->


    <!-- Bootstrap Bundle with Popper -->
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0/dist/js/bootstrap.bundle.min.js"
            integrity="sha384-p34f1UUtsS3wqzfto5wAAmdvj+osOnFyQFpp4Ua3gs/ZVWx6oOypYoCJhGGScy+8"
            crossorigin="anonymous"></script>

</body>
</html>

src/pages/templates/pages/home-page.html
{% extends 'pages/base.html' %}

{% block page_title_tag %} Simple Blog Landing Page {% endblock %}
{% block page_meta_description %} Place to share lovable content. {% endblock %}
{% block page_meta_keywords %} blog, love, share {% endblock %}

{% load static %}

{% block content %}
<div class="px-4 pt-5 my-3 text-center border-bottom">
    <!--<p>{{ msg }}</p>-->
    <h1 class="display-4 fw-bold">My Simple Blog</h1>
    <div class="col-lg-6 mx-auto">
        <p class="lead mb-4">This is a simple blog that I am putting together to place within my portfolio. This blog makes use of the Bootstrap CSS Framework, Django and Python. I also add a lot of cool features that I fee are just critical, well not critical but important for developing online web applications.</p>
        <div class="d-grid gap-2 d-sm-flex justify-content-sm-center mb-5">
            <button type="button" class="btn btn-primary btn-lg px-4 me-sm-3">Primary button</button>
            <button type="button" class="btn btn-outline-secondary btn-lg px-4">Secondary</button>
        </div>
    </div>
    <div class="overflow-hidden" style="max-height: 30vh;">
        <div class="container px-5">
            <img src="{% static 'pages/img/dev_bootstrap-docs.jpg' %}" class="img-fluid border rounded-3 shadow-lg mb-4" alt="Example image"
                 width="700" height="500" loading="lazy">
        </div>
    </div>
</div>
{% endblock content %}

src/pages/templates/pages/page.html
{% extends 'pages/base.html' %}

{% block page_title_tag %} PAGE TITLE {% endblock %}
{% block page_meta_description %} PAGE META DESCRIPTION {% endblock %}
{% block page_meta_keywords %} PAGE META KEYWORDS {% endblock %}

{% load static %}

{% block content %}
PAGE CONTENT (AKA the BODY)
{% endblock content %}

src/pages/templates/pages/partials/footer.html
<div class="container-fluid text-center">
    Visit me at <a href="https://BootupYourTech.com" target="_blank">https://BootupYourTech.com</a>
</div>

src/pages/templates/pages/partials/header.html
{% load static %}

<header class="container d-flex flex-wrap align-items-center justify-content-center justify-content-md-between py-3 mb-4 border-bottom">
    <a href="{% url 'pages:home' %}" class="d-flex align-items-center col-md-3 mb-2 mb-md-0 text-dark text-decoration-none">
        <img id="boostrap-logo" width="50px" src="{% static 'pages/img/bootstrap5-logo-black.svg' %}" alt="My Simple Blog Logo" draggable="false">
    </a>

    <ul class="nav col-12 col-md-auto mb-2 justify-content-center mb-md-0">
        <li><a href="{% url 'pages:home' %}" class="nav-link px-2 link-secondary">Home</a></li>
        <li><a href="/admin" class="nav-link px-2 link-dark disabled">Admin</a></li>
        <li><a href="#" class="nav-link px-2 link-dark disabled">My List</a></li>
        <li><a href="#" class="nav-link px-2 link-dark disabled">My Post</a></li>
        <li><a href="https://www.notion.so/" target="_blank" class="nav-link px-2 link-dark">Notion</a></li>
    </ul>

    <div class="col-md-3 text-end">
        <button type="button" class="btn btn-primary">Sign-up</button>
        <button type="button" class="btn btn-outline-primary me-2">Login</button>
        <button type="button" class="btn btn-outline-primary me-2">Logout</button>
    </div>
</header>